In [2]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
# Sentences

sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
vocab_size = 10000

In [8]:
## One Hot Representation
one_hot_repr = [one_hot(words, vocab_size) for words in sent]

In [9]:
one_hot_repr

[[9658, 235, 5163, 3016],
 [9658, 235, 5163, 2867],
 [9658, 9386, 5163, 4244],
 [1978, 3341, 9794, 1415, 536],
 [1978, 3341, 9794, 1415, 5976],
 [4924, 9658, 5624, 5163, 4692],
 [6648, 5970, 5015, 1415]]

In [14]:
## word embedding representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences -> has been removed, hence the below import statement is used
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [19]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9658  235 5163 3016]
 [   0    0    0    0 9658  235 5163 2867]
 [   0    0    0    0 9658 9386 5163 4244]
 [   0    0    0 1978 3341 9794 1415  536]
 [   0    0    0 1978 3341 9794 1415 5976]
 [   0    0    0 4924 9658 5624 5163 4692]
 [   0    0    0    0 6648 5970 5015 1415]]


In [20]:
## feature representation
dim=10

In [21]:
model=Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam','mse')

c:\Users\Meenatchi\Desktop\Deep Learning Folder\ann_venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[[-2.53213290e-02, -4.80081700e-02,  6.68560341e-03,
         -1.68030858e-02, -4.05740850e-02, -4.97438088e-02,
          3.07242908e-02,  1.27656385e-03, -3.27751637e-02,
         -1.13751888e-02],
        [-2.53213290e-02, -4.80081700e-02,  6.68560341e-03,
         -1.68030858e-02, -4.05740850e-02, -4.97438088e-02,
          3.07242908e-02,  1.27656385e-03, -3.27751637e-02,
         -1.13751888e-02],
        [-2.53213290e-02, -4.80081700e-02,  6.68560341e-03,
         -1.68030858e-02, -4.05740850e-02, -4.97438088e-02,
          3.07242908e-02,  1.27656385e-03, -3.27751637e-02,
         -1.13751888e-02],
        [-2.53213290e-02, -4.80081700e-02,  6.68560341e-03,
         -1.68030858e-02, -4.05740850e-02, -4.97438088e-02,
          3.07242908e-02,  1.27656385e-03, -3.27751637e-02,
         -1.13751888e-02],
        [-2.63333917e-02,  8.71174410e-03, -2.03711390e-02,
         -3.41052637e-02,  4.61139716e-02, -9.33555514e-03,
         -1.20302215e-02,  1.58791281e-02, -9.608067

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 9658,  235, 5163, 3016], dtype=int32)